name: AuthLib
version: '${version}'
main: ru.mentola.authlib.AuthLib
api-version: '1.20'
commands:
  auth:
    description: "Authorization"
    aliases:
      - log
      - login
  register:
    description: "Register"
    aliases:
      - reg
depend:
  - packetevents